package io.github.estivensh4.kotlinmultiplatformwizard.common.utils

object TemplateGroup {
    const val PACKAGE_NAME = "com.example"
    const val COMPOSE_PROJECT_GRADLE = "project_build.gradle.kts"
    const val ANDROID_MAINACTIVITY = "android_mainactivity.kt"
    const val ANDROID_MANIFEST = "android_manifest.xml"
    const val COMMON_APP = "common_app.kt"
    const val COMMON_BUILD = "common_build.gradle.kts"
    const val COMMON_PLATFORM = "common_platform.kt"
    const val DEFAULT_PLATFORM = "default_platform.kt"
    const val JVM_PLATFORM = "jvm_platform.kt"
    const val DESKTOP_MAIN = "desktop_main.kt"
    const val IOS_IOSAPP = "ios_iosapp.swift"
    const val IOS_PLATFORM = "ios_platform.kt"
    const val IOS_PROJECT = "ios_project.pbxproj"
    const val WASM_JS_MAIN = "wasm_js_main.kt"
    const val COMPOSE_WASM_JS_MAIN = "compose_wasm_js_main.kt"
    const val PROJECT_GRADLE = "project_gradle.properties"
    const val PROJECT_SETTINGS = "project_settings.gradle.kts"
    const val PROJECT_TOML = "libs.versions.toml"
    const val GRADLE_WRAPPER_PROPERTIES = "gradle_wrapper.properties"
    const val COMPOSE_GRADLE_KTS = "compose.gradle.kts"
    const val ANDROID_VALUES_XML = "values.xml"
    const val COMMON_COMPOSE_RESOURCES_MULTIPLATFORM_XML = "compose_multiplatform.xml"
    const val COMPOSE_IOS_MAIN = "compose_ios_main.kt"
    const val SERVER_APP_MAIN = "server_app.kt"
    const val SERVER_LOGBACK = "logback.xml"
    const val SERVER_BUILD_GRADLE_KTS = "server_build.gradle.kts"
    const val SHARED_CONSTANTS = "shared_constants.kt"
    const val SHARED_GREETING = "shared_greeting.kt"
    const val IOS_APP_CONFIGURATION = "config.xcconfig"
    const val WASMJS_INDEX_HTML = "wasmjs_index.html"
    const val WASMJS_STYLES_CSS = "wasmjs_styles.css"
    const val IOS_CONTENTVIEW_SWIFT = "ios_contentview.swift"
    const val IOS_ICONS_CONTENTS_JSON = "ios_icons_contents.json"
    const val IOS_COLORS_CONTENTS_JSON = "ios_colors_contents.json"
    const val IOS_ASSETS_CONTENTS_JSON = "ios_assets_contents.json"
    const val IOS_PREVIEW_CONTENTS_JSON = "ios_preview_contents.json"
    const val IOS_INFO_PLIST = "ios_info.plist"
}